# =============================================================================
# main.py — FastAPI application entry point
# =============================================================================

from contextlib import asynccontextmanager

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse

from app.config import settings
from app.database import init_db
from app.routes import sales


# ---------------------------------------------------------------------------
# Lifespan — replaces deprecated @app.on_event("startup/shutdown")
# ---------------------------------------------------------------------------
@asynccontextmanager
async def lifespan(app: FastAPI):
    # ── Startup ──────────────────────────────────────────────────────────────
    print(f"🚀 Starting {settings.APP_NAME} v{settings.APP_VERSION}")
    await init_db()
    print("✅ Database tables verified")
    yield
    # ── Shutdown ─────────────────────────────────────────────────────────────
    print("🛑 Application shutting down")


# ---------------------------------------------------------------------------
# App instance
# ---------------------------------------------------------------------------
app = FastAPI(
    title=settings.APP_NAME,
    version=settings.APP_VERSION,
    description="""
## Retail Sales Analytics API

Exposes pre-computed Gold-layer analytics generated by the
**Azure Databricks / PySpark** pipeline.

### Data Flow
```
CSV → ADF → ADLS Bronze → Databricks Silver → Gold → PostgreSQL → This API
```

### Key Endpoints
| Endpoint | Description |
|---|---|
| `/api/v1/sales/summary` | Executive KPI dashboard card |
| `/api/v1/sales/daily-revenue` | Day-by-day revenue trend |
| `/api/v1/sales/top-products` | Revenue-ranked product list |
| `/api/v1/sales/store-performance` | Store leaderboard |
| `/api/v1/sales/category-trends` | Weekly category roll-up |
    """,
    lifespan=lifespan,
    docs_url="/docs",
    redoc_url="/redoc",
)

# ---------------------------------------------------------------------------
# Middleware
# ---------------------------------------------------------------------------
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],         # tighten to specific domains in production
    allow_credentials=True,
    allow_methods=["GET"],       # read-only API
    allow_headers=["*"],
)


# ---------------------------------------------------------------------------
# Routers
# ---------------------------------------------------------------------------
app.include_router(sales.router)


# ---------------------------------------------------------------------------
# Health + Meta endpoints
# ---------------------------------------------------------------------------
@app.get("/health", tags=["Meta"], summary="Health check")
async def health_check():
    """Used by Docker / Kubernetes liveness probes."""
    return {"status": "healthy", "version": settings.APP_VERSION}


@app.get("/", tags=["Meta"], include_in_schema=False)
async def root():
    return JSONResponse({
        "message": "Retail Sales Analytics API",
        "docs": "/docs",
        "health": "/health",
    })